apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: default
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done",
            ]
      containers:
        - name: migrate
          image: mini-databricks-migrate:latest
          imagePullPolicy: Never
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mini-databricks-secrets
                  key: db-url
